# Site settings
title: Yin's Blog
email:
description: "Riffs."
baseurl: ""
url: "https://github.com/wangyin717"
twitter_username: wangyin717
github_username: wangyin717

# Build settings
markdown: redcarpet
permalink: pretty
